id: P004467
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG17022
  title: འུ་ཟི་ཇ་རྫོང་།
  author: ''
  volumes:
    bca97e2fa0064127991fb39f990f0c99:
      image_group_id: I1KG17118
      title: ''
      volume_number: 1
      total_pages: 374
      base_file: v001.txt
